# CRORIS Projekti API pt.2

Second part of data importing, after the API is called, we are now processing the raw response saved in a .csv

In [311]:
#imports
import pandas as pd
import json
import time
import datetime
import ast
from contextlib import suppress

drive_path = 'data/'

In [310]:
# initiate dataframes
df_ustanova = pd.DataFrame(columns=['id','mbu','ustanovaNaziv','aaiDomain','created'])#done
df_osoba = pd.DataFrame(columns=['id','osobaPoirotId','ime','prezime','ustanovaId','created'])#done
df_projekt = pd.DataFrame(columns=['id','projektPoirotId','hrSifraProjekta','tipProjekta_id','acro',
                                   'pocetak','kraj','currencyCode','totalCost','title','summary','financijer_id','created'])#done
df_financijer = pd.DataFrame(columns=['id','financijerPoirotId','entityId','entityNameHr','entityNameEn',
                                      'vrstaIzvoraFinanciranjaId','vrstaIzvoraFinanciranjaName','pozivId','pozivNaziv','created'])#done
# relational dfs
df_osoba_projekt = pd.DataFrame(columns=['osoba_id','projekt_id','pocetak','kraj','projektnaUloga','created'])#done
df_projekt_financijer = pd.DataFrame(columns=['projekt_id','financijer_id','created'])#done
df_projekt_tip = pd.DataFrame(columns=['projekt_id','tipProjektaId','tipProjektaNaziv','created'])#done
df_projekt_ustanova = pd.DataFrame(columns=['projekt_id','ustanova_id','amount','currencyCode','klasifikacijaNaziv','created'])#done

In [312]:
# function for populating pandas dfs
def populate_dfs(response,df_ustanova,df_osoba,df_projekt,df_financijer,df_osoba_projekt,df_projekt_financijer,df_projekt_tip,df_projekt_ustanova):
    #initiate variables
    projekt_id,tipProjektaId,tipProjektaNaziv,projektPoirotId,hrSifraProjekta,tipProjekta_id,acro,pocetak,kraj,currencyCode,totalCost,title,summary,financijer_id = (None,)*14
    
    with suppress(KeyError): projekt_id = response['id']
    with suppress(KeyError): tipProjektaId = response['tipProjekta']['id']
    with suppress(KeyError): tipProjektaNaziv = response['tipProjekta']['naziv']
    with suppress(KeyError): projektPoirotId = response['projektPoirotId']   
    with suppress(KeyError): hrSifraProjekta = response['hrSifraProjekta']
    with suppress(KeyError): tipProjekta_id = response['tipProjekta']['id']
    with suppress(KeyError): acro = response['acro']
    with suppress(KeyError): pocetak = response['pocetak']
    with suppress(KeyError): kraj = response['kraj']
    with suppress(KeyError): currencyCode = response['currencyCode']
    with suppress(KeyError): totalCost = response['totalCost']
    with suppress(KeyError): title = response['title'][0]['naziv']
    with suppress(KeyError): summary = response['summary'][0]['naziv']
    with suppress(KeyError): financijer_id = response['financijerResources']['_embedded']['financijeri'][0]['id']
    with suppress(KeyError): created = datetime.datetime.now()

    try:
        response['ustanoveResources']
    except:
        print(projekt_id, '- Nema ustanove!')
    else:
        #iterate over USTANOVA and save as pandas df together with relation with projekt
        for ustanova in response['ustanoveResources']['_embedded']['ustanove']: 
            ustanova_id,mbu,ustanovaNaziv,aaiDomain,amount,currencyCode,klasifikacijaNaziv,ustanovaPocetak,ustanovaKraj = (None,)*9
            #ustanova
            with suppress(KeyError): ustanova_id = ustanova['id']
            with suppress(KeyError): mbu = ustanova['mbu']
            with suppress(KeyError): ustanovaNaziv = ustanova['naziv']
            with suppress(KeyError): aaiDomain = ustanova['aaiDomain']

            #projekt ustanova relation
            with suppress(KeyError): amount = ustanova['amount']
            with suppress(KeyError): currencyCode = ustanova['currencyCode']
            with suppress(KeyError): klasifikacijaNaziv = ustanova['klasifikacija']['naziv']
            with suppress(KeyError): ustanovaPocetak = ustanova['pocetak']
            with suppress(KeyError): ustanovaKraj = ustanova['kraj']
      
            #save each ustanova from projekt
            df_ustanova = pd.concat([df_ustanova, pd.DataFrame(data= {'id' :ustanova_id,
                                                        'mbu' :mbu,
                                                        'ustanovaNaziv' :ustanovaNaziv,
                                                        'aaiDomain' :aaiDomain,
                                                        'created' :created}, index=[0])])
            
            #save each relation between ustanova and projekt
            df_projekt_ustanova = pd.concat([df_projekt_ustanova, pd.DataFrame(data={'projekt_id' :projekt_id,
                                                              'ustanova_id' :ustanova_id,
                                                              'amount' :amount,
                                                              'currencyCode' :currencyCode,
                                                              'klasifikacijaNaziv' :klasifikacijaNaziv,
                                                              'pocetak' :ustanovaPocetak,
                                                              'kraj' :ustanovaKraj,
                                                              'created' :created}, index=[0])])

    try:
        response['osobeResources']
    except:
        print(projekt_id, '- Nema osobe!')
    else:
        #iterate over all OSOBA from projekt and save to pandas dfs
        for osoba in response['osobeResources']['_embedded']['osobe']:
            osobaPoirotId,persId,ime,prezime,projektnaUloga,ustanovaId,pocetak,kraj = (None,)*8
            with suppress(KeyError): osobaPoirotId = osoba['osobaPoirotId']
            with suppress(KeyError): persId = osoba['persId']
            with suppress(KeyError): ime = osoba['ime']
            with suppress(KeyError): prezime = osoba['prezime']
            with suppress(KeyError): projektnaUloga = osoba['klasifikacija']['naziv']
            with suppress(KeyError): ustanovaId = osoba['ustanovaId']
            with suppress(KeyError): pocetak = osoba['pocetak']
            with suppress(KeyError): kraj = osoba['kraj']

            #save each osoba from projekt
            df_osoba = pd.concat([df_osoba, pd.DataFrame(data= {'id' :persId,
                                                      'osobaPoirotId' :osobaPoirotId,
                                                      'ime' :ime,
                                                      'prezime' :prezime,
                                                      'ustanovaId' :ustanovaId,
                                                      'created' :created}, index=[0])])
            
            #save osoba projekt relation
            df_osoba_projekt = pd.concat([df_osoba_projekt, pd.DataFrame(data= {'osoba_id' :persId,
                                                              'projekt_id' :projekt_id,
                                                              'pocetak' :pocetak,
                                                              'kraj' :kraj,
                                                              'projektnaUloga' :projektnaUloga,
                                                              'created' :created}, index=[0])])

    #save PROJEKT details to pandas df
    df_projekt = pd.concat([df_projekt, pd.DataFrame(data={'id' :projekt_id,
                                              'projektPoirotId' :projektPoirotId,
                                              'hrSifraProjekta' :hrSifraProjekta,
                                              'tipProjekta_id' :tipProjekta_id,
                                              'acro' :acro,
                                              'pocetak' :pocetak,
                                              'kraj' :kraj,
                                              'currencyCode' :currencyCode,
                                              'totalCost' :totalCost,
                                              'title' :title,
                                              'summary' :summary,
                                              'financijer_id' :financijer_id,
                                              'created' :created}, index=[0])])
    
    #iterate over FINANCIJER and save as pandas df together with relation with projekt
    try:
        response['financijerResources']
    except:
        print(projekt_id, '- Nema financijera!')
    else:
        for financijer in response['financijerResources']['_embedded']['financijeri']:
            financijer_id,financijerPoirotId,entityId,entityNameHr,entityNameEn,vrstaIzvoraFinanciranjaId,vrstaIzvoraFinanciranjaName,pozivId,pozivNaziv=(None,)*9
            with suppress(KeyError): financijer_id = financijer['id']
            with suppress(KeyError): financijerPoirotId = financijer['financijerPoirotId']
            with suppress(KeyError): entityId = financijer['entityId']
            with suppress(KeyError): entityNameHr = financijer['entityNameHr']
            with suppress(KeyError): entityNameEn = financijer['entityNameEn']
            with suppress(KeyError): vrstaIzvoraFinanciranjaId = financijer['vrstaIzvoraFinanciranjaId']
            with suppress(KeyError): vrstaIzvoraFinanciranjaName = financijer['vrstaIzvoraFinanciranjaName']
            with suppress(KeyError): pozivId = financijer['pozivId'] 
            with suppress(KeyError): pozivNaziv = financijer['pozivNaziv']

            #save each financijer from projekt
            df_financijer = pd.concat([df_financijer, pd.DataFrame(data={'id' :financijer_id,
                                                      'financijerPoirotId' :financijerPoirotId,
                                                      'entityId' :entityId,
                                                      'entityNameHr' :entityNameHr,
                                                      'entityNameEn' :entityNameEn,
                                                      'vrstaIzvoraFinanciranjaId' :vrstaIzvoraFinanciranjaId,
                                                      'vrstaIzvoraFinanciranjaName' :vrstaIzvoraFinanciranjaName,
                                                      'pozivId' :pozivId,
                                                      'pozivNaziv' :pozivNaziv,
                                                      'created' :created}, index=[0])])
            
            #save each financijer from projekt
            df_projekt_financijer = pd.concat([df_projekt_financijer, pd.DataFrame(data={'projekt_id' :projekt_id,
                                                          'financijer_id' :financijer_id,
                                                          'created' :created}, index=[0])])

    #save each tip projekta
    df_projekt_tip = pd.concat([df_projekt_tip, pd.DataFrame(data={'projekt_id' :projekt_id,
                                                          'tipProjektaId' :tipProjektaId,
                                                          'tipProjektaNaziv' :tipProjektaNaziv,
                                                          'created' :created}, index=[0])])
    
    return df_ustanova,df_osoba,df_projekt,df_financijer,df_osoba_projekt,df_projekt_financijer,df_projekt_tip,df_projekt_ustanova

In [313]:
# read the scrapped API responses saved in csv to df
df_response = pd.read_csv(drive_path+'CRORIS_df_response.csv', index_col=0)

In [316]:
# MAIN
for index, row in df_response.iterrows():
    response = ast.literal_eval(row['response'])
    #print(response['id'])
    # call function populate_dfs() and assign returned dfs to our pandas dfs
    df_ustanova,df_osoba,df_projekt,df_financijer,df_osoba_projekt,df_projekt_financijer,df_projekt_tip,df_projekt_ustanova = populate_dfs(response,df_ustanova,df_osoba,df_projekt,df_financijer,df_osoba_projekt,df_projekt_financijer,df_projekt_tip,df_projekt_ustanova)
    
print("END")

526 - Nema financijera!
527 - Nema financijera!
528 - Nema financijera!
529 - Nema financijera!
530 - Nema financijera!
531 - Nema financijera!
532 - Nema financijera!
533 - Nema financijera!
534 - Nema financijera!
574 - Nema osobe!
609 - Nema osobe!
678 - Nema ustanove!
678 - Nema osobe!
711 - Nema ustanove!
711 - Nema osobe!
795 - Nema osobe!
2866 - Nema osobe!
3189 - Nema osobe!
3190 - Nema osobe!
3191 - Nema osobe!
3195 - Nema osobe!
3201 - Nema osobe!
3202 - Nema osobe!
3204 - Nema osobe!
3206 - Nema osobe!
3207 - Nema osobe!
3208 - Nema osobe!
3212 - Nema osobe!
3213 - Nema osobe!
3215 - Nema osobe!
3224 - Nema osobe!
3230 - Nema osobe!
3266 - Nema osobe!
3480 - Nema osobe!
3481 - Nema osobe!
3484 - Nema osobe!
3486 - Nema osobe!
3487 - Nema osobe!
3488 - Nema osobe!
3490 - Nema osobe!
3491 - Nema osobe!
3492 - Nema osobe!
3493 - Nema osobe!
3494 - Nema osobe!
3495 - Nema osobe!
3496 - Nema osobe!
3497 - Nema osobe!
3498 - Nema osobe!
3499 - Nema osobe!
3503 - Nema osobe!
3504 - Nema osobe!
3505 - Nema osobe!
3506 - Nema osobe!
3507 - Nema osobe!
3508 - Nema osobe!
3509 - Nema osobe!
3510 - Nema osobe!
3512 - Nema osobe!
3513 - Nema osobe!
3514 - Nema osobe!
3515 - Nema osobe!
3517 - Nema osobe!
3519 - Nema osobe!
3520 - Nema osobe!
3521 - Nema osobe!
3605 - Nema osobe!
3606 - Nema osobe!
3607 - Nema osobe!
3616 - Nema osobe!
3618 - Nema osobe!
3622 - Nema osobe!
3626 - Nema osobe!
3627 - Nema osobe!
3629 - Nema osobe!
3630 - Nema osobe!
3631 - Nema osobe!
3633 - Nema osobe!
3636 - Nema osobe!
3637 - Nema osobe!
3638 - Nema osobe!
3787 - Nema osobe!
3788 - Nema osobe!
3795 - Nema osobe!
3798 - Nema osobe!
3801 - Nema osobe!
4333 - Nema osobe!
4338 - Nema osobe!
4339 - Nema osobe!
4340 - Nema osobe!
4345 - Nema osobe!
4347 - Nema osobe!
4350 - Nema osobe!
4353 - Nema osobe!
4354 - Nema osobe!
4357 - Nema osobe!
4360 - Nema osobe!
4364 - Nema osobe!
4365 - Nema osobe!
4366 - Nema osobe!
4368 - Nema osobe!
4369 - Nema osobe!
6542 - Nema ustanove!
6542 - Nema osobe!
6641 - Nema ustanove!
6642 - Nema ustanove!
6642 - Nema osobe!
6809 - Nema ustanove!
6809 - Nema osobe!
7697 - Nema ustanove!
7697 - Nema financijera!
7698 - Nema ustanove!
7698 - Nema financijera!
7709 - Nema ustanove!
7709 - Nema financijera!
7714 - Nema financijera!
7715 - Nema financijera!
7716 - Nema financijera!
7717 - Nema osobe!
7717 - Nema financijera!
7718 - Nema financijera!
7720 - Nema financijera!
7721 - Nema financijera!
7723 - Nema financijera!
7724 - Nema financijera!
7725 - Nema financijera!
7729 - Nema ustanove!
7729 - Nema financijera!
7732 - Nema financijera!
7739 - Nema ustanove!
7739 - Nema financijera!
7740 - Nema financijera!
7741 - Nema ustanove!
7741 - Nema financijera!
END

In [319]:
df_osoba_projekt.tail()
#len(df_osoba)

,osoba_id,projekt_id,pocetak,kraj,projektnaUloga,created
0,34728,7749,01.12.2021,30.09.2022,voditelj,2022-09-24 22:58:32.107991
0,39075,7749,01.12.2021,30.09.2022,suradnik,2022-09-24 22:58:32.107991
0,30703,7750,01.12.2021,06.05.2022,voditelj,2022-09-24 22:58:32.122292
0,21999,7752,01.07.2018,01.07.2020,voditelj na ustanovi,2022-09-24 22:58:32.131546
0,5518,7755,01.10.2021,30.09.2024,voditelj na ustanovi,2022-09-24 22:58:32.140600

In [268]:
# time conversion in pandas
df_projekt['pocetak'] = pd.to_datetime(df_projekt['pocetak'], format = "%d.%m.%Y")
df_projekt['kraj'] = pd.to_datetime(df_projekt['kraj'], format = "%d.%m.%Y")

In [271]:
#drop duplicates from all pandas dfs
df_ustanova = df_ustanova.drop_duplicates(subset='id', keep='last')
df_osoba = df_osoba.drop_duplicates(subset='id', keep='last')
df_projekt = df_projekt.drop_duplicates(subset='id', keep='last')
df_financijer = df_financijer.drop_duplicates(subset='id', keep='last')
df_osoba_projekt = df_osoba_projekt.drop_duplicates(subset=['osoba_id','projekt_id'], keep='last')
df_projekt_financijer = df_projekt_financijer.drop_duplicates(subset=['projekt_id','financijer_id'],keep='last')
df_projekt_tip = df_projekt_tip.drop_duplicates(subset='projekt_id', keep='last')
df_projekt_ustanova = df_projekt_ustanova.drop_duplicates(subset=['projekt_id','ustanova_id'], keep='last')

In [294]:
df_ustanova.to_csv('CRORIS_df_ustanova.csv')
df_osoba.to_csv('CRORIS_df_osoba.csv')
df_projekt.to_csv('CRORIS_df_projekt.csv')
df_financijer.to_csv('CRORIS_df_financijer.csv')
df_osoba_projekt.to_csv('CRORIS_df_osoba_projekt.csv')
df_projekt_financijer.to_csv('CRORIS_df_projekt_financijer.csv')
df_projekt_tip.to_csv('CRORIS_df_projekt_tip.csv')
df_projekt_ustanova.to_csv('CRORIS_df_projekt_ustanova.csv')